apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
  namespace: app-internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
