# create secrets for seafile
# do not commit this file with real passwords!

apiVersion: v1
kind: Secret
metadata:
  name: seafile-admin
  namespace: app-internal
type: Opaque
stringData:
  email: liangmichael27822@gmail.com
  password: Nshd20020811!
