# create secrets for bytebase
# do not commit this file with real passwords!

apiVersion: v1
kind: Secret
metadata:
  name: bytebase-db
  namespace: database
type: Opaque
stringData:
  # postgresql connection url
  url: "postgresql://postgres:uyOFTOH1lEvOxc854owatEQPffzjWcqGYsk0X1swcFFb3buBZDcHZ95MEaey1svQ@postgres-lb:5432/bytebase"
  username: postgres
  password: uyOFTOH1lEvOxc854owatEQPffzjWcqGYsk0X1swcFFb3buBZDcHZ95MEaey1svQ
