apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: app-internal
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer 
  dnsNames:
    - vault.mikey-liang.com