apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls
  namespace: app-internal
spec:
  secretName: immich-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - photos.mikey-liang.com
