apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless-tls
  namespace: app-internal
spec:
  secretName: paperless-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - docs.mikey-liang.com
