apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-tls
  namespace: app-internal
spec:
  secretName: glance-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - hub.mikey-liang.com
