# create secrets for postgres cluster
# do not commit this file with real passwords!

apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: CHANGE_ME_STRONG_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-user
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: CHANGE_ME_APP_PASSWORD
