# create secrets for redis
# do not commit this file with real passwords!

apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: database
type: Opaque
stringData:
  # redis password for master and sentinel
  # generate with: openssl rand -base64 32
  password: FR1UUY+YeRSbJpeFz1QZqjW448MjuzhdPL2iokGrTYk=
